/*
@license
Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
!function(e){"use strict";var t=e.querySelector("#app");t.apiBaseUrl="http://localhost:5001/",t.services={dashboard:t.apiBaseUrl+"dashboard"},t.baseUrl="/",""===window.location.port&&(t.baseUrl="/tpa-bootstrap/"),t.menuItems=[{route:"home",title:"Home",icon:"tpa:home"},{route:"users",title:"Users",icon:"tpa:users"},{route:"contact",title:"Contact",icon:"tpa:email"},{route:"settings",title:"Settings",icon:"tpa:settings"}],t.displayInstalledToast=function(){Polymer.dom(e).querySelector("platinum-sw-cache").disabled||Polymer.dom(e).querySelector("#caching-complete").show()},t.addEventListener("dom-change",function(){console.log("Our app is ready to rock!")}),window.addEventListener("WebComponentsReady",function(){}),window.addEventListener("open-menu",function(){t.$.paperDrawerPanel.togglePanel()}),t.scrollPageToTop=function(){t.$.headerPanelMain.scrollToTop(!0)},addEventListener("iron-deselect",function(e){"mainPages"===e.target.id&&t.menuItemSelected(e.target)}),t.menuItemSelected=function(e){var a=e.items.find(function(e){return e.attributes["data-route"].value==t.data.pageName});t.data.pageName.length>0&&!a&&(t.$.toast.text="Can't find: "+window.location.href+". Redirected you to Home Page",t.$.toast.show()),t.$.paperDrawerPanel.closeDrawer()},t.closeDrawer=function(){t.$.paperDrawerPanel.closeDrawer()}}(document);